SET_PAL_BATTLE_BLACK         EQU $00
SET_PAL_BATTLE               EQU $01
SET_PAL_TOWN_MAP             EQU $02
SET_PAL_STATUS_SCREEN        EQU $03
SET_PAL_POKEDEX              EQU $04
SET_PAL_SLOTS                EQU $05
SET_PAL_TITLE_SCREEN         EQU $06
SET_PAL_NIDORINO_INTRO       EQU $07
SET_PAL_GENERIC              EQU $08
SET_PAL_OVERWORLD            EQU $09
SET_PAL_PARTY_MENU           EQU $0A
SET_PAL_POKEMON_WHOLE_SCREEN EQU $0B
SET_PAL_GAME_FREAK_INTRO     EQU $0C
SET_PAL_TRAINER_CARD         EQU $0D
UPDATE_PARTY_MENU_BLK_PACKET EQU $FC

; super game boy palettes
const_value = 0

	const PAL_ROUTE     ; $00
	const PAL_PALLET    ; $01
	const PAL_VIRIDIAN  ; $02
	const PAL_PEWTER    ; $03
	const PAL_CERULEAN  ; $04
	const PAL_LAVENDER  ; $05
	const PAL_VERMILION ; $06
	const PAL_CELADON   ; $07
	const PAL_FUCHSIA   ; $08
	const PAL_CINNABAR  ; $09
	const PAL_INDIGO    ; $0A
	const PAL_SAFFRON   ; $0B
	const PAL_TOWNMAP   ; $0C
	const PAL_LOGO1     ; $0D
	const PAL_LOGO2     ; $0E
	const PAL_0F        ; $0F
	const PAL_MEWMON    ; $10
	const PAL_BLUEMON   ; $11
	const PAL_REDMON    ; $12
	const PAL_CYANMON   ; $13
	const PAL_PURPLEMON ; $14
	const PAL_BROWNMON  ; $15
	const PAL_GREENMON  ; $16
	const PAL_PINKMON   ; $17
	const PAL_YELLOWMON ; $18
	const PAL_GREYMON   ; $19
	const PAL_SLOTS1    ; $1A
	const PAL_SLOTS2    ; $1B
	const PAL_SLOTS3    ; $1C
	const PAL_SLOTS4    ; $1D
	const PAL_BLACK     ; $1E
	const PAL_GREENBAR  ; $1F
	const PAL_YELLOWBAR ; $20
	const PAL_REDBAR    ; $21
	const PAL_BADGE     ; $22
	const PAL_CAVE      ; $23
	const PAL_GAMEFREAK ; $24
	const PAL_25        ; $25
	const PAL_26        ; $26
	const PAL_27        ; $27
	const PAL_BULBASAUR  ; $28
	const PAL_IVYSAUR    ; $29
	const PAL_VENUSAUR   ; $2A
	const PAL_CHARMANDER ; $2B
	const PAL_CHARMELEON ; $2C
	const PAL_CHARIZARD  ; $2D
	const PAL_SQUIRTLE   ; $2E 
	const PAL_BLASTOISE  ; $2F
	const PAL_CATERPIE   ; $30
	const PAL_METAPOD    ; $31
	const PAL_BUTTERFREE ; $32
	const PAL_WEEDLE     ; $33
	const PAL_KAKUNA     ; $34
	const PAL_BEEDRILL   ; $35
	const PAL_PIDGEY     ; $36
	const PAL_PIDGEOTTO  ; $37
	const PAL_RATTATA    ; $38
	const PAL_RATICATE   ; $39
	const PAL_SPEAROW    ; $3A
	const PAL_FEAROW     ; $3B
	const PAL_EKANS      ; $3C
	const PAL_ARBOK      ; $3D
	const PAL_PIKACHU    ; $3E
	const PAL_RAICHU     ; $3F
	const PAL_SANDSHREW  ; $40
	const PAL_SANDSLASH  ; $41
	const PAL_NIDORAN_F  ; $42
	const PAL_NIDORINA   ; $43
	const PAL_NIDOQUEEN  ; $44
	const PAL_NIDORAN_M  ; $45
	const PAL_NIDOKING   ; $46
	const PAL_CLEFAIRY   ; $47
	const PAL_VULPIX     ; $48
	const PAL_NINETALES  ; $49
	const PAL_JIGGLYPUFF ; $4A
	const PAL_ZUBAT      ; $4B
	const PAL_ODDISH     ; $4C
	const PAL_GLOOM      ; $4D
	const PAL_VILEPLUME  ; $4E
	const PAL_PARAS      ; $4F
	const PAL_PARASECT   ; $50
	const PAL_VENONAT    ; $51
	const PAL_VENOMOTH   ; $52
	const PAL_DIGLETT    ; $53
	const PAL_MEOWTH     ; $54
	const PAL_PERSIAN    ; $55
	const PAL_PSYDUCK    ; $56
	const PAL_GOLDUCK    ; $57
	const PAL_MANKEY     ; $58
	const PAL_PRIMEAPE   ; $59
	const PAL_GROWLITHE  ; $5A
	const PAL_POLIWAG    ; $5B
	const PAL_POLIWHIRL  ; $5C
	const PAL_POLIWRATH  ; $5D
	const PAL_ABRA       ; $5E
	const PAL_MACHOP     ; $5F
	const PAL_MACHOKE    ; $60
	const PAL_MACHAMP    ; $61
	const PAL_BELLSPROUT ; $62
	const PAL_WEEPINBELL ; $63
	const PAL_VICTREEBEL ; $64
	const PAL_TENTACOOL  ; $65
	const PAL_TENTACRUEL ; $66
	const PAL_GEODUDE    ; $67
	const PAL_GRAVELER   ; $68
	const PAL_PONYTA     ; $69
	const PAL_SLOWPOKE   ; $6A
	const PAL_SLOWBRO    ; $6B
	const PAL_MAGNEMITE  ; $6C
	const PAL_FARFETCHD  ; $6D
	const PAL_DODUO      ; $6E
	const PAL_DODRIO     ; $6F
	const PAL_SEEL       ; $70
	const PAL_DEWGONG    ; $71
	const PAL_GRIMER     ; $72
	const PAL_SHELLDER   ; $73
	const PAL_CLOYSTER   ; $74
	const PAL_GASTLY     ; $75
	const PAL_HAUNTER    ; $76
	const PAL_GENGAR     ; $77
	const PAL_ONIX       ; $78
	const PAL_DROWZEE    ; $79
	const PAL_HYPNO      ; $7A
	const PAL_KRABBY     ; $7B
	const PAL_VOLTORB    ; $7C
	const PAL_EXEGGCUTE  ; $7D
	const PAL_EXEGGUTOR  ; $7E
	const PAL_CUBONE     ; $7F
	const PAL_HITMONLEE  ; $80
	const PAL_HITMONCHAN ; $81
	const PAL_LICKITUNG  ; $82
	const PAL_KOFFING    ; $83
	const PAL_RHYHORN    ; $84
	const PAL_CHANSEY    ; $85
	const PAL_TANGELA    ; $86
	const PAL_KANGASKHAN ; $87
	const PAL_HORSEA     ; $88
	const PAL_SEADRA     ; $89
	const PAL_GOLDEEN    ; $8A
	const PAL_SEAKING    ; $8B
	const PAL_STARYU     ; $8C
	const PAL_STARMIE    ; $8D
	const PAL_MR_MIME    ; $8E
	const PAL_SCYTHER    ; $8F
	const PAL_JYNX       ; $90
	const PAL_ELECTABUZZ ; $91
	const PAL_MAGMAR     ; $92
	const PAL_PINSIR     ; $93
	const PAL_TAUROS     ; $94
	const PAL_MAGIKARP   ; $95
	const PAL_GYARADOS   ; $96
	const PAL_LAPRAS     ; $97
	const PAL_DITTO      ; $98
	const PAL_EEVEE      ; $99
	const PAL_VAPOREON   ; $9A
	const PAL_JOLTEON    ; $9B
	const PAL_FLAREON    ; $9C
	const PAL_PORYGON    ; $9D
	const PAL_OMANYTE    ; $9E
	const PAL_KABUTO     ; $9F
	const PAL_AERODACTYL ; $A0
	const PAL_SNORLAX    ; $A1
	const PAL_ARTICUNO   ; $A2
	const PAL_ZAPDOS     ; $A3
	const PAL_MOLTRES    ; $A4
	const PAL_DRATINI    ; $A5
	const PAL_DRAGONAIR  ; $A6
	const PAL_DRAGONITE  ; $A7
	const PAL_MEWTWO     ; $A8
	const PAL_MEW        ; $A9
	; Trainer palettes
	const PAL_YOUNGSTER     ; $AA
	const PAL_BUGCATCHER    ; $AB
	const PAL_LASS          ; $AC
	const PAL_SAILOR        ; $AD
	const PAL_JR_TRAINER_M  ; $AE
	const PAL_JR_TRAINER_F  ; $AF
	const PAL_POKEMANIAC    ; $B0
	const PAL_SUPERNERD     ; $B1
	const PAL_HIKER         ; $B2
	const PAL_BIKER         ; $B3
	const PAL_BURGLAR       ; $B4
	const PAL_ENGINEER      ; $B5
	const PAL_JUGGLER       ; $B6
	const PAL_FISHERMAN     ; $B7
	const PAL_SWIMMER       ; $B8
	const PAL_CUEBALL       ; $B9
	const PAL_GAMBLER       ; $BA
	const PAL_BEAUTY        ; $BB
	const PAL_PSYCHIC       ; $BC
	const PAL_ROCKER        ; $BD
	const PAL_TAMER         ; $BE
	const PAL_BIRDKEEPER    ; $BF
	const PAL_BLACKBELT     ; $C0
	const PAL_GARY          ; $C1
	const PAL_OAK           ; $C2
	const PAL_SCIENTIST     ; $C3
	const PAL_GIOVANNI      ; $C4
	const PAL_ROCKET        ; $C5
	const PAL_COOLTRAINER   ; $C6
	const PAL_BROCK         ; $C7
	const PAL_MISTY         ; $C8
	const PAL_LT_SURGE      ; $C9
	const PAL_ERIKA         ; $CA
	const PAL_KOGA          ; $CB
	const PAL_BLAINE        ; $CC
	const PAL_SABRINA       ; $CD
	const PAL_GENTLEMAN     ; $CE
	const PAL_LORELEI       ; $CF
	const PAL_CHANNELER     ; $D0
	const PAL_AGATHA        ; $D1
	const PAL_LANCE         ; $D2
	const PAL_HERO          ; $D3
	; New Pokemon palettes
	const PAL_SNUBBULL      ; $D4
	const PAL_HOOTHOOT      ; $D5
	const PAL_NOCTOWL       ; $D6
	const PAL_HANNECO       ; $D7
	const PAL_POPOCO        ; $D8
	const PAL_WATACO        ; $D9
	const PAL_CLEFFA        ; $DA
	const PAL_IGGLYBUFF     ; $DB
	const PAL_CROBAT        ; $DC
	const PAL_MIKON         ; $DD
	const PAL_SLOWKING      ; $DE
	const PAL_PUDIE         ; $DF
	const PAL_TURBAN        ; $E0
	const PAL_MADAME        ; $E1
	const PAL_DODRE         ; $E2
	const PAL_GRIMBLER      ; $E3
	const PAL_STEELIX       ; $E4
	const PAL_REMORAID      ; $E5
	const PAL_OCCUTANK      ; $E6
	const PAL_KOTORA        ; $E7
	const PAL_RAITORA       ; $E8
	const PAL_BLISSEY       ; $E9
	const PAL_KINGDRA       ; $EA
	const PAL_GOYPIN        ; $EB
	const PAL_BAIRINA       ; $EC
	const PAL_SMOOCHUM      ; $ED
	const PAL_ELEKID        ; $EE
	const PAL_MAGBY         ; $EF
	const PAL_MANTINE       ; $F0
	const PAL_WOLFMAN       ; $F1